# Generated by Django 2.1.5 on 2019-01-30 11:32

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_auto_20190130_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypath',
            name='spots',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, sort_value_field_name='id', to='geo_object.GeoObject'),
        ),
    ]
