# Generated by Django 2.1.5 on 2019-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_auto_20190130_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypath',
            name='spots',
            field=models.ManyToManyField(to='geo_object.GeoObject'),
        ),
    ]
